# Generated by Django 2.2.3 on 2019-10-06 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPublicacion', models.DateTimeField(verbose_name='date published')),
                ('textoPregunta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textoRespuesta', models.CharField(max_length=200)),
                ('preguntaPerteneciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preguntas.Pregunta')),
            ],
        ),
    ]
